# .zprofile is basically the same as .zlogin except that it's sourced before
# .zshrc while .zlogin is sourced instead of directly after it.
# According to the zsh documentation, ".zprofile is meant as an alternative to
# .zlogin for ksh fans; the two are not intended to be used together, although
# this could certainly be done if desired."

# load order: .zshenv < .zprofile < .zshrc < .zlogin < .zlogout

# no common config for now
