
#####################
# mint: a swift package manager that builds executables
export MINT_PATH=/Volumes/NoSave/Users/Shared/Library/Caches/mint
export MINT_LINK_PATH=/usr/local/bin

# pipx: a python executables package manager with virtual environments
#
# TODO: rebuild using /Users/Shared/opt@
export PIPX_GLOBAL_HOME=/Volumes/NoSave/Users/Shared/Library/Caches/pipx
export PIPX_HOME="$PIPX_GLOBAL_HOME"
export PIPX_GLOBAL_BIN_DIR=/usr/local/bin
export PIPX_BIN_DIR="$PIPX_GLOBAL_BIN_DIR"
export PIPX_GLOBAL_MAN_DIR=/usr/local/share/man
export PIPX_MAN_DIR="$PIPX_GLOBAL_MAN_DIR"
#export PIPX_SHARED_LIBS=

# rustup
# This is the location that rustup stores its (downloaded) toolchains
export RUSTUP_HOME=/Users/Shared/Library@/Developer/rustup/
# rustup binaries for cargo, rustc, etc which redirect to the active toolchain:
#   $(brew --prefix rustup)/bin
# which can be added to PATH as needed.
