# .zshrc is for interactive shell configuration. You set options for the
# interactive shell there with the setopt and unsetopt commands. You can also
# load shell modules, set your history options, change your prompt, set up zle
# and completion, et cetera. You also set any variables that are only used in
# the interactive shell (e.g. $LS_COLORS).

# load order: .zshenv < .zprofile < .zshrc < .zlogin < .zlogout

# https://gist.github.com/ClementNerma/1dd94cb0f1884b9c20d1ba0037bdcde2
# zsh Cheat Sheet


PS1='%S%n@%m %1~ %#%s '
# inverse video prompt

setopt extended_glob
# more ways to get unexpected file expansions


fpath+=/Users/Shared/Configs@/_/share/zsh/site-functions
# Add my zsh "functions" (just scripts, really) to zsh functions path
#
autoload -Uz $fpath[-1]/*(.:t)
### declare site-functions/* files as functions # (.:t) => basename

alias ls='ls -F'

config_zvm
# set the line editor to vi-like, and load ZVM plugin to switch mode cursors


#SHH: NOTE: all PATH addenda are done in .zshenv

#SHH: Files not used:
# .zlogin
#   is sourced on the start of a login shell but after .zshrc if the
#   shell is also interactive. This file is often used to start X using startx.
#   Some systems start X on boot, so this file is not always very useful.
# .zlogout
#   is sometimes used to clear and reset the terminal. It is called when
#   exiting, not when opening.
